version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: moneywaste
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
#    volumes:
#      - $PWD/docker-data/prod/postgres-data:/var/lib/postgresql/data


#volumes:
#  postgres-data:



